#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-nanotest
Version  : 0.9.4.1
Release  : 6
URL      : https://rubygems.org/downloads/nanotest-0.9.4.1.gem
Source0  : https://rubygems.org/downloads/nanotest-0.9.4.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rdoc

%description
*"Frustra fit per plura quod potest fieri per pauciora."* --William of Ockham
"It is futile to do with more things that which can be done with fewer."

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n nanotest-0.9.4.1
gem spec %{SOURCE0} -l --ruby > rubygem-nanotest.gemspec

%build
gem build rubygem-nanotest.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
nanotest-0.9.4.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/nanotest-0.9.4.1 && ruby -v -I.:lib test/test_nanotest.rb && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/nanotest-0.9.4.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/nanotest-0.9.4.1/ri/Nanotest/assert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/nanotest-0.9.4.1/ri/Nanotest/cdesc-Nanotest.ri
/usr/lib64/ruby/gems/2.2.0/doc/nanotest-0.9.4.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/Manifest
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/examples.rb
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/gem.watchr
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/lib/nanotest.rb
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/markdown.watchr
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/nanotest.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/specs.watchr
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/nanotest-0.9.4.1/test/test_nanotest.rb
/usr/lib64/ruby/gems/2.2.0/specifications/nanotest-0.9.4.1.gemspec
